In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# seaborn에서 제공하는 그래프테마
# sns.set_style("ticks")
# sns.set_style("darkgrid")
sns.set_style("whitegrid")

# 그래프를 그리기 위한 기본 설정
# 폰트설정 - 윈도우
plt.rcParams['font.family'] = 'Malgun Gothic'

# 폰트설정 - 맥
# plt.rcParams['font.family'] = 'Apple Gothic'

# 그래프의 크기
plt.rcParams['figure.figsize'] = 12, 6

# 글자 크기
plt.rcParams['font.size'] = 14

# 폰트 설정 시 '-'기호 깨는거 방지하기
plt.rcParams['axes.unicode_minus'] = False

### 데이터 읽어오기

In [5]:
# 데이터를 읽어올 때 사용할 주소
site = 'https://www.basketball-reference.com/leagues/NBA_2018_games.html'
# read_html : 지정된 페이지에 table 태그가 있을 경우 table 태그 하나당 하나의 데이터프레임을 생성한다.
tables = pd.read_html(site)
tables[0]

,Date,Start (ET),Visitor/Neutral,PTS,Home/Neutral,PTS.1,Unnamed: 6,Unnamed: 7,Attend.,Notes
0,"Tue, Oct 17, 2017",8:01p,Boston Celtics,99,Cleveland Cavaliers,102,Box Score,NaN,20562,NaN
1,"Tue, Oct 17, 2017",10:30p,Houston Rockets,122,Golden State Warriors,121,Box Score,NaN,19596,NaN
2,"Wed, Oct 18, 2017",7:00p,Charlotte Hornets,90,Detroit Pistons,102,Box Score,NaN,20491,NaN
3,"Wed, Oct 18, 2017",7:00p,Brooklyn Nets,131,Indiana Pacers,140,Box Score,NaN,15008,NaN
4,"Wed, Oct 18, 2017",7:00p,Miami Heat,109,Orlando Magic,116,Box Score,NaN,18846,NaN
...,...,...,...,...,...,...,...,...,...,...
99,"Mon, Oct 30, 2017",10:30p,Golden State Warriors,141,Los Angeles Clippers,113,Box Score,NaN,19068,NaN
100,"Tue, Oct 31, 2017",7:00p,Sacramento Kings,83,Indiana Pacers,101,Box Score,NaN,12245,NaN
101,"Tue, Oct 31, 2017",7:30p,Phoenix Suns,122,Brooklyn Nets,114,Box Score,NaN,12936,NaN
102,"Tue, Oct 31, 2017",8:00p,Oklahoma City Thunder,110,Milwaukee Bucks,91,Box Score,NaN,16713,NaN
103,"Tue, Oct 31, 2017",10:30p,Detroit Pistons,93,Los Angeles Lakers,113,Box Score,NaN,17569,NaN